const a = 2;
const b = 3;
console.log(`a = ${a}`);
console.log(`b = ${b}`);
console.log(`a + b = ${a + b}`);
console.log(`a - b = ${a - b}`);
console.log(`a * b = ${a * b}`);
console.log(`a / b = ${Math.floor(a / b)}`);
console.log(`a % b = ${a % b}`);